mysql:
  build: $DB_DOCKERFILE_DIR
  ports:
    - "23306:3306"
  environment:
    MYSQL_DATABASE : myapp_development
    MYSQL_USER : myapp
    MYSQL_PASSWORD : myapp_pass
    MYSQL_ROOT_PASSWORD : _root_

redis:
  build: $REDIS_DOCKERFILE_DIR
  ports:
    - "6379:6379"

webapp:
  build: $WEBAPP_DOCKERFILE_DIR
  ports:
    - "9000:8080"
    - "3000:3000"
  links:
    - mysql:mysql
    - redis:redis
  volumes:
    - ${APP_ROOT_DIR}:/var/data
  environment:
    RAILS_DATABASE_HOST : mysql
  command: /var/scripts/start_webapp.sh

